/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author invitado
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    int contDec, contSeg, contMin;
    public void actualizarCrono(){
        lblDeci.setText("0" + contDec);
        if(contSeg < 10)
            lblSeg.setText("0" + contSeg);
        
        lblSeg.setText("0" + contSeg);
        if(contMin < 10)
            lblMin.setText("0" + contMin);
    }
    Runnable runnable = new Runnable()
    {

        @Override
        public void run() {
            while(true){
                actualizarCrono();
                if(contDec == 9){
                    contDec=0;
                    //Incrementar segundos
                if(contSeg == 59){
                    contSeg=0;
                    //Incrementar minutos
                if(contMin == 63){
                    contMin=0;
                    //Incrementar minutos    
                }else
                    contDec++;
                else
                    contSeg++;
                else
                    contMin++;
                try{
                    Thread.sleep(100);
                }catch(InterruptedException ex){
                    
                }
            }
        }
    };
    Thread crono;
    
    public NewJFrame() {
        initComponents();
        
        crono = new Thread(runnable);
        
        contDec=0;
        contSeg=0;
        contMin=0;
        
        this.setLocationRelativeTo(null);
        this.setSize(500,350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSeg = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnReanudar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblDeci = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMin.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblMin.setText("00");
        getContentPane().add(lblMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 112, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText(":");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 112, -1, -1));

        lblSeg.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblSeg.setText("00");
        getContentPane().add(lblSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 112, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Iniciar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 235, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Detener");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 235, -1, -1));

        btnReanudar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReanudar.setText("Reanudar");
        btnReanudar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReanudarMouseClicked(evt);
            }
        });
        getContentPane().add(btnReanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 235, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setText(".");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 112, -1, -1));

        lblDeci.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblDeci.setText("00");
        getContentPane().add(lblDeci, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 112, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Decimas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 72, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Segundos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 72, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Minutos");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        crono.start();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        crono.suspend();
    }//GEN-LAST:event_jButton2MouseClicked

    private void btnReanudarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReanudarMouseClicked
        // TODO add your handling code here:
        crono.stop();
    }//GEN-LAST:event_btnReanudarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReanudar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblDeci;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblSeg;
    // End of variables declaration//GEN-END:variables
}
