
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MandoParra 22550032
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private boolean cerrar;
    public NewJFrame() {
        initComponents();
        cerrar = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTrabar = new javax.swing.JButton();
        btnJF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTrabar.setText("Trabar programa");
        btnTrabar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrabarMouseClicked(evt);
            }
        });
        btnTrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 65, -1, -1));

        btnJF.setText("JUST FOR FUN!!");
        btnJF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJFMouseClicked(evt);
            }
        });
        getContentPane().add(btnJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 65, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrabarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrabarMouseClicked
        // TODO add your handling code here:
        Runnable runnable = new Runnable() {

            @Override
            public void run() { //Aqui va la tarea que se ejecuta en un hilo
                //Ciclo infinito
                while(true){
                    try {
                        Thread.sleep(1);
                        System.out.println(".");
                    } catch (InterruptedException ex) {
                        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(cerrar){
                        System.out.println("Terminando hilo de ejecucion!!!");
                    break;
                    }
                }     
            }
        };
       // runnable.run();//Si lo ejecuto directamente este llama directamente al while
        //THREAD es un hilo
        Thread miHilo = new Thread(runnable);
        miHilo.start();
    }//GEN-LAST:event_btnTrabarMouseClicked

    private void btnJFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJFMouseClicked
        // TODO add your handling code here:
        System.out.println("El boton funciona perfectamente!!!");
        dispose();
    }//GEN-LAST:event_btnJFMouseClicked

    private void btnTrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrabarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // Cierra completamente
        cerrar = true;
        System.out.println("Cerrando Pantalla");
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.out.println("Cerrando");
        dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJF;
    private javax.swing.JButton btnTrabar;
    // End of variables declaration//GEN-END:variables
}
